### ISSUE TITLE
Maven central repository

### ISSUE THREAD

**Issue by zik43** [Tuupertunut/PowerShellLibJava#1]
Hello,

we would like to use your library in our Maven project, could you please upload it on the Maven Central Repository (https://mvnrepository.com/repos/central) ?

Best regards

**Comment by Tuupertunut** [comment]
Yes, this is planned.

**Comment by Tuupertunut** [comment]
Done.
https://mvnrepository.com/artifact/com.github.tuupertunut/powershell-lib-java
