### ISSUE TITLE
Exception is not handled properly

### ISSUE THREAD

**Issue by rajeevuipath** [Tuupertunut/PowerShellLibJava#10]
I am facing a issue where executing a simple powershell command like ```throw "some exception"``` is not handled properly. Program will get indefinitely stuck waiting for the output
Example code
```
try(PowerShell powershell = PowerShell.open()){
	System.out.println(powershell.executeCommands("Write-Error 'The file does not exist';throw \"abc\";Write-Error 'The file does not exist';"));
}catch(Exception e){
    e.printStackTrace();
}
```

**Comment by Tuupertunut** [comment]
I can confirm this. It seems that the PowerShell command `Invoke-Expression` will catch all other exceptions happening inside it except those caused by `throw`.

**Comment by Tuupertunut** [comment]
I am currently not interested in investigating this further, but I welcome any pull requests.

**Comment by Tuupertunut** [comment]
Fixed
