### ISSUE TITLE
Need to synchronize executecommands

### ISSUE THREAD

**Issue by BZValoche** [Tuupertunut/PowerShellLibJava#11]
Hi,
I have to project with a webservice giving information on Windows printers, using powershell commands. For the sake of performance (open is slow), I open a powershell session when m API server starts, which is used for all the requests.
When executecommands() gets called in parallel, it sometimes fails wxith a StringIndexOutOfBoundsException. You probably want to make this method synchronized (whith I did to solve this problem).
Rgds,
BZ
![exception](https://user-images.githubusercontent.com/48053275/53485386-5fdf2900-3a86-11e9-85b4-22bc8680a3a4.png)
Valoche

**Comment by Tuupertunut** [comment]
The library is not intended to be thread safe. Making executeCommands synchronized will probably end most concurrency problems, but I'm not sure if it will end all of them. If you have ideas on how to make this library thread safe, you can make a pull request and I will see.

**Comment by Tuupertunut** [comment]
This library will be kept non-thread safe for now. If you need to call executeCommands in parallel, make your own synchronized method that calls executeCommands.
