### ISSUE TITLE
Single file library

### ISSUE THREAD

**Issue by charphi** [Tuupertunut/PowerShellLibJava#14]
The big advantage of your library is that it is very lightweight: there are only three files in it.

I wonder if you could go even further and reduce it into one single file? (such as [picocli](https://picocli.info/))
The main benefit would be to easily include it as source and therefore avoid adding dependencies.

**Comment by Tuupertunut** [comment]
Isn't it kind of an anti-pattern to include libraries as sources? As to why I think it couldn't be one file, AsyncReaderRecorder and PowerShell are very different classes and wouldn't fit well together.

**Comment by charphi** [comment]
It might be an anti-pattern indeed.

My purpose is to follow a [zero-dependency policy](https://blog.jooq.org/2016/08/11/all-libraries-should-follow-a-zero-dependency-policy/) in my libraries.
Therefore I need to repackage the dependencies of my libraries.

I've tried maven shade plugin. This plugin relocates dependencies by modifiying byte code directly. Unfortunatly, it doesn't repackage module-info classes (JPMS).

The second solution I've found so far is to to automate source extraction of dependecies to a second source directory before the compilation of all the source code (lib + dependencies). Having a single source file eases this.

`AsyncReaderRecorder` and `PowerShell` are indeed very different classes. My guess is that `AsyncReaderRecorder` could be moved into `PowerShell` as a private class if it has no use outside of the library itself.

**Comment by Tuupertunut** [comment]
Ok, I see. Your use case is quite special. Unfortunately I have no interest in changing the architecture of this library, as it fits most use cases just fine. The best solution would probably be to include all 3 files as source. Or I guess you could create something that packs everything into one class as inner classes.
