### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by pedrogcsb** [Tuupertunut/PowerShellLibJava#17]
Hey,

Any way of stoping the exception to be thrown when powershell retrieves error? Thanks

**Comment by Tuupertunut** [comment]
This library is designed to throw a Java exception whenever PowerShell writes something to error output. There is no builtin way to disable this. You can however wrap your PowerShell code in PowerShell try-catch and handle all PowerShell errors yourself. Do you have any ideas on how to improve error handling in this library?
