### ISSUE TITLE
handling output

### ISSUE THREAD

**Issue by iKrushYou** [Tuupertunut/PowerShellLibJava#2]
Hi, I landed on your project after browsing and testing jPowerShell

Seeing that you're a bit more active on this project, i have a question: Do you have any consideration for how to handle powershell outputs of objects? Possibly in the form of json? 

I currently have a powershell server running which accepts incoming http requests with a PowerShell command as the input, then it executes the command and returns the output as json. This works great until you hit it with a lot of traffic. It's not multi-threaded so I'm looking to make a java server to do just this.

Let me know if you have any thoughts

Best,
Alex

**Comment by Tuupertunut** [comment]
The scope of this project is to allow text-based communication between Java and PowerShell, so writing out custom output formats is left to the user. You can convert your objects to Json inside PowerShell easily with `ConvertTo-Json` command (https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-json?view=powershell-6).

**Comment by iKrushYou** [comment]
I suppose I hadn't thought about converting it before every command returns it but that could work! 

Thanks

**Comment by iKrushYou** [comment]
@Tuupertunut follow up question, but unrelated, do you know how I can make sure the PS session is run as admin?

**Comment by Tuupertunut** [comment]
PowerShell command
```
([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
```
will return a boolean describing whether the PS session has admin rights.
