### ISSUE TITLE
Strange behavior of ProcessBuilder

### ISSUE THREAD

**Issue by charphi** [Tuupertunut/PowerShellLibJava#8]
I have a strage bug that appends when I use your library in a NetBeans Platform application on Windows.

The first call to `PowerShell#executeCommands(String...)` throws an exception `Parameter format not correct - ">"`. But subsequent calls on the same session are fine!

The problem might come from `PowerShell#createProcessBuilder(String)`. The character `>` seems to be escaped when run.

I can reproduce this problem by typing in `chcp 65001 ">" NUL & echo hello` in a terminal prompt.

My current solution is to replace the process builder command by :  
```java
new ProcessBuilder("cmd", "/c", "chcp 65001 > NUL", "&", psExecutable, "-ExecutionPolicy", "Bypass", "-NoExit", "-Command", "-");
```

Do you know why `ProcessBuilder` would change its behavior?

**Comment by Tuupertunut** [comment]
What type of exception it is?

**Comment by charphi** [comment]
Sorry for my late reply, I was on a vacation.

The exception is the following:
```
com.github.tuupertunut.powershelllibjava.PowerShellExecutionException: Error while executing PowerShell commands:
Parameter format not correct - ">"

	at com.github.tuupertunut.powershelllibjava.PowerShell.executeCommands(PowerShell.java:258)
```

It seems that the error is already present in `errorOuputRecorder` before calling `executeCommands`.

**Comment by Tuupertunut** [comment]
Yeah, if the constructor executes powershell code that throws a powershell error, it will be stored inside AsyncReaderRecorder and thrown when the recorder is called next time. This is why it throws PowerShellExecutionException on the first command. The problem seems to be the > character. Investigating.

**Comment by Tuupertunut** [comment]
This is hard for me to reproduce. Could you try executing some script in PowerShellLibJava that takes very long, such as `Start-Sleep -s 10000`. Then while it is running open a PowerShell console and execute `Get-CimInstance Win32_Process -Filter "Name = 'cmd.exe'" | Select-Object -Property CommandLine` to see the starting commands of currently running cmd processes. Find the one representing the cmd command of PowerShellLibJava and paste it here.

**Comment by charphi** [comment]
Here is the command:
`"cmd" /c chcp 65001 ">" NUL & powershell -ExecutionPolicy Bypass -NoExit -Command -`

**Comment by Tuupertunut** [comment]
That's weird. Your system is quoting some parts of it but not all.

**Comment by charphi** [comment]
Indeed and it only appends when called in a NetBeans Platform application.

**Comment by charphi** [comment]
As written in my first post, the only solution I've found so far is to merge some parameters in the process builder:

from 

```java 
new ProcessBuilder("cmd", "/c", "chcp", "65001", ">", "NUL", "&", psExecutable, "-ExecutionPolicy", "Bypass", "-NoExit", "-Command", "-")
```
to 

```java 
new ProcessBuilder("cmd", "/c", "chcp 65001 > NUL", "&", psExecutable, "-ExecutionPolicy", "Bypass", "-NoExit", "-Command", "-")
```

**Comment by Tuupertunut** [comment]
Yeah, I guess most platforms use space as delimiter anyway so the processbuilder command could just be one string.

**Comment by charphi** [comment]
I've done some digging and the problem comes from the availability of a security manager at runtime in `java.lang.ProcessImpl:358`.

So, if a security manager is not defined (null), the escaping is soft and doesn't escape char `>` (see `VERIFICATION_LEGACY`).

On the other hand, if a security manager is defined (not null), the escaping is more strict and it escapes char `>` (see `VERIFICATION_WIN32`).

Here is a copy-paste from the jdk:
```java
    private static final int VERIFICATION_CMD_BAT = 0;
    private static final int VERIFICATION_WIN32 = 1;
    private static final int VERIFICATION_LEGACY = 2;
    private static final char ESCAPE_VERIFICATION[][] = {
        // We guarantee the only command file execution for implicit [cmd.exe] run.
        //    http://technet.microsoft.com/en-us/library/bb490954.aspx
        {' ', '\t', '<', '>', '&', '|', '^'},

        {' ', '\t', '<', '>'},
        {' ', '\t'}
    };
```

**Comment by Tuupertunut** [comment]
Fixed.

**Comment by charphi** [comment]
Thanks
